version: "3.1"

services:
  
  api:
    build: ./demo-movie-api
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
  

  app:
    build: ./demo-movie-react
    restart: always
    ports:
      - 3000:3000

  migration:
    build:
      context: ./demo-movie-api
      dockerfile: Dockerfile.migration
    depends_on:
      db:
        condition: service_healthy
    command: npm run migrate:up
  
  seed:
    build:
      context: ./demo-movie-api
      dockerfile: Dockerfile.migration
    depends_on:
      migration:
        condition: service_completed_successfully
    command: npm run seed:all

  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=root
      - POSTGRES_DB=movie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080


networks:
  default:
    driver: bridge